[tool.poetry]
name = "bdbot"
version = "4.8.1"
description = "A discord bot that post comics strip."
authors = ["Arik <BBArik@protonmail.com>"]
license = "GPL 3.0"

[tool.poetry.dependencies]
python = "^3.9"
"discord.py" = "^2.3.2"
requests = "^2.32.0"
rss-parser = "^2.0.0"
beautifulsoup4 = "^4.12.3"
python-dotenv = "^1.0.1"
randomtimestamp = "^2.2"
topggpy = "^1.4.0"
inquirerpy = "^0.3.4"
poetry = "^1.8.3"

[tool.poetry.dev-dependencies]
pytest = "^8.2.0"
flake8 = "^7.0.0"
isort = "^5.13.2"
black = "^24.4.2"
pre-commit = "^3.7.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
bdbot = "bdbot.__main__:main"
bdbot_manager = 'bdbot.bdbot_manager:main'
