[tool.poetry]
name = "bdbot"
version = "4.6"
description = "A discord bot that post comics strip."
authors = ["Arik <BBArik@protonmail.com>"]
license = "GPL 3.0"

[tool.poetry.dependencies]
python = "^3.9"
"discord.py" = "^2.0.1"
requests = "^2.28.1"
rss-parser = "^0.2.4"
beautifulsoup4 = "^4.11.1"
python-dotenv = "^0.21.0"
randomtimestamp = "^2.2"
topggpy = "^1.4.0"
inquirerpy = "^0.3.4"
poetry = "^1.3.1"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
flake8 = "^6.0.0"
isort = "^5.11.3"
black = "^22.12.0"
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
bdbot = "bdbot.__main__:main"
bdbot_manager = 'bdbot.bdbot_manager:main'