[tool.poetry]
name = "bdbot"
version = "4.7"
description = "A discord bot that post comics strip."
authors = ["Arik <BBArik@protonmail.com>"]
license = "GPL 3.0"

[tool.poetry.dependencies]
python = "^3.9"
"discord.py" = "^2.3.0"
requests = "^2.28.2"
rss-parser = "^1.0.0"
beautifulsoup4 = "^4.12.2"
python-dotenv = "^1.0.0"
randomtimestamp = "^2.2"
topggpy = "^1.4.0"
inquirerpy = "^0.3.4"
poetry = "^1.4.2"

[tool.poetry.dev-dependencies]
pytest = "^7.3.1"
flake8 = "^6.0.0"
isort = "^5.12.0"
black = "^23.3.0"
pre-commit = "^3.2.2"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
bdbot = "bdbot.__main__:main"
bdbot_manager = 'bdbot.bdbot_manager:main'
